Some syntax fixes to ELK Listener, add new fields from message defini…
RHQE/platform-ci pull request #43
Opened 2016-12-13 18:57 UTC by johnbieren

Fixed a syntax error that will cause failure, made the parameters at the bottom a little more clear, added the new field from the message definition, and moved the printing of the environment up so debugging failures is easier.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

2016-12-14 03:01 UTC, lulinqing requested changes

2016-12-14 03:01 UTC, lulinqing commented on ELK_Listener/ci_listener.yaml
> +                 print "%s=%s" % (key, os.environ[key])
Shall we always use "print( )" syntax (python3 compatible)?
Didn't notice this earlier. Other print lines seem good.

2016-12-14 03:01 UTC, lulinqing commented on ELK_Listener/ci_listener.yaml
> +                 expected_Keys=['component', 'trigger', 'tests', 'job_link_back', 'base_distro', 'compose_id', 'brew_task_id', 'create_time', 'completion_time', 'CI_infra_failure', 'CI_infra_failure_
We are changing 'job_link_back' to 'jenkins_job_url' as discussed in the doc.
Cc @jcanderle in case doc needs update accordingly too.

2016-12-14 12:07 UTC, johnbieren commented on ELK_Listener/ci_listener.yaml
> +                 print "%s=%s" % (key, os.environ[key])
Good catch, fixed

2016-12-14 12:07 UTC, johnbieren commented on ELK_Listener/ci_listener.yaml
> +                 expected_Keys=['component', 'trigger', 'tests', 'job_link_back', 'base_distro', 'compose_id', 'brew_task_id', 'create_time', 'completion_time', 'CI_infra_failure', 'CI_infra_failure_
Right, forgot about that.  Fixed

2016-12-16 15:06 UTC, lulinqing approved these changes

2016-12-16 15:07 UTC, merged